# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - LICENSE

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-${{ matrix.vs }}

    strategy:
      fail-fast: false

      matrix:
        vs: [2019, 2022]
        build_type: [Debug, Release]
        platform: [x86, x64, ARM64]

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: 'Instance templates'
      shell: pwsh
      working-directory: ${{ github.workspace }}/VSIX
      run: |
        .\createmsbuild.ps1 d3d11game_win32 Direct3DGame ${{ github.workspace }}
        .\createmsbuild.ps1 d3d11game_win32_dr Direct3DGameDR ${{ github.workspace }}
        .\createmsbuild.ps1 d3d12game_win32 Direct3D12Game ${{ github.workspace }}
        .\createmsbuild.ps1 d3d12game_win32_dr Direct3D12GameDR ${{ github.workspace }}
        .\createmsbuild.ps1 d3d11game_uwp Direct3DUWPGame ${{ github.workspace }}
        .\createmsbuild.ps1 d3d11game_uwp_dr Direct3DUWPGameDR ${{ github.workspace }}
        .\createmsbuild.ps1 d3d12game_uwp Direct3DUWP12Game ${{ github.workspace }}
        .\createmsbuild.ps1 d3d12game_uwp_dr Direct3DUWP12GameDR ${{ github.workspace }}
        .\createmsbuild.ps1 d3d11game_uwp_cppwinrt Direct3DUWPGameCPP ${{ github.workspace }}
        .\createmsbuild.ps1 d3d11game_uwp_cppwinrt_dr Direct3DUWPGameDRCPP ${{ github.workspace }}
        .\createmsbuild.ps1 d3d12game_uwp_cppwinrt Direct3DUWP12GameCPP ${{ github.workspace }}
        .\createmsbuild.ps1 d3d12game_uwp_cppwinrt_dr Direct3DUWP12GameDRCPP ${{ github.workspace }}

    - name: 'Build - Direct3DGame'
      working-directory: ${{ github.workspace }}/Direct3DGame
      run: msbuild /m /p:Configuration=${{ matrix.build_type }} /p:Platform=${{ matrix.platform }} Direct3DGame.vcxproj

    - name: 'Build - Direct3DUWPGame'
      working-directory: ${{ github.workspace }}/Direct3DUWPGame
      run: msbuild /m /p:Configuration=${{ matrix.build_type }} /p:Platform=${{ matrix.platform }} Direct3DUWPGame.vcxproj

    - name: 'Build - Direct3DUWPGameCPP'
      working-directory: ${{ github.workspace }}/Direct3DUWPGameCPP
      run: msbuild /m /p:Configuration=${{ matrix.build_type }} /p:Platform=${{ matrix.platform }} Direct3DUWPGameCPP.vcxproj
      