# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Microsoft C++ Code Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - LICENSE
  schedule:
    - cron: '25 15 * * 5'

permissions:
  contents: read

jobs:
  analyze:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Analyze
    runs-on: windows-latest

    strategy:
      fail-fast: false

      matrix:
        template: [d3d11game_win32, d3d11game_win32_dr, d3d12game_win32, d3d12game_win32_dr]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: 'Instance template'
        shell: pwsh
        working-directory: ${{ github.workspace }}/VSIX
        run: |
          .\createcmake.ps1  ${{ matrix.template }} TestProject ${{ github.workspace }}

      - name: Configure CMake
        working-directory: ${{ github.workspace }}/TestProject
        run: cmake -B out -DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON

      - name: Initialize MSVC Code Analysis
        uses: microsoft/msvc-code-analysis-action@v0.1.1
        id: run-analysis
        with:
          cmakeBuildDirectory: ./out
          buildConfiguration: Debug
          ruleset: NativeRecommendedRules.ruleset

      # Upload SARIF file to GitHub Code Scanning Alerts
      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.run-analysis.outputs.sarif }}
