# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Microsoft C++ Code Analysis

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"
    paths-ignore:
      - '*.md'
      - LICENSE
  schedule:
    - cron: '25 15 * * 5'

permissions:
  contents: read

jobs:
  analyze:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Analyze
    runs-on: windows-latest

    strategy:
      fail-fast: false

      matrix:
        # action fails on the VCPKG case so skipping d3d12game_vcpkg for now
        template: [
          d3d11game_win32,
          d3d11game_win32_dr,
          d3d12game_win32,
          d3d12game_win32_dr,
          d3d11game_uwp_cppwinrt,
          d3d11game_uwp_cppwinrt_dr,
          d3d12game_uwp_cppwinrt,
          d3d12game_uwp_cppwinrt_dr
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          arch: amd64

      - name: 'Instance template'
        shell: pwsh
        working-directory: ${{ github.workspace }}/VSIX
        run: |
          .\createcmake.ps1  ${{ matrix.template }} TestProject ${{ github.workspace }}

      - if: ${{ contains(matrix.template, 'win32') }}
        name: 'Configure CMake for Win32'
        working-directory: ${{ github.workspace }}/TestProject
        run: cmake -B out -DBUILD_TEST_TEMPLATE=ON -DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON

      - if: ${{ contains(matrix.template, 'uwp') }}
        name: 'Configure CMake for UWP'
        working-directory: ${{ github.workspace }}/TestProject
        run: >
          cmake -B out -DCMAKE_SYSTEM_NAME="WindowsStore" -DCMAKE_SYSTEM_VERSION="10.0"
          -DBUILD_TEST_TEMPLATE=ON -DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON

      - if: ${{ contains(matrix.template, 'vcpkg') }}
        name: 'Configure CMake for VCPKG'
        working-directory: ${{ github.workspace }}/TestProject
        run: |
          $toolchain = "$env:VCPKG_ROOT\scripts\buildsystems\vcpkg.cmake" -replace '\\','/'
          $args = @(
            '-B'
            'out'
            '-DBUILD_TEST_TEMPLATE=ON'
            '-DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON'
            '-DVCPKG_MANIFEST_MODE=ON'
            '-DVCPKG_MANIFEST_DIR=${{ github.workspace }}\TestProject'
            '-DCMAKE_TOOLCHAIN_FILE="${toolchain}"'
          )
          $echoargs = @("/c", "echo")
          Start-Process -NoNewWindow -FilePath "cmd.exe" -ArgumentList ($echoargs + $args)
          Start-Process -NoNewWindow -FilePath "cmake.exe" -ArgumentList $args

      - name: Initialize MSVC Code Analysis
        uses: microsoft/msvc-code-analysis-action@24c285ab36952c9e9182f4b78dfafbac38a7e5ee # v0.1.1
        id: run-analysis
        with:
          cmakeBuildDirectory: ./TestProject/out
          buildConfiguration: Debug
          ruleset: NativeRecommendedRules.ruleset
          ignoredPaths: ${{ github.workspace }}/TestProject/out/vcpkg_installed

      # Upload SARIF file to GitHub Code Scanning Alerts
      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@ce28f5bb42b7a9f2c824e633a3f6ee835bab6858 # v3.29.0
        with:
          sarif_file: ${{ steps.run-analysis.outputs.sarif }}
